server:
  port: 8888

spring:
  application:
    name: ocrClient
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

logging:
  charset:
    console: UTF-8
    file: UTF-8
  file:
    path: ./logs
