server:
  port: 8888

spring:
  application:
    name: ocrClient
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:sqlite:sqlite/ocr.db3
    driver-class-name: org.sqlite.JDBC

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml


snapshot-camera:
  output-folder-path: D:/output
  file-name-prefix: SnapShot
  image-format: png
